export const getCategoriesAction = {
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",
};

export const cartProductsAction = {
  ADD_PRODUCTS_START: "ADD_PRODUCTS_START",
  ADD_PRODUCTS_SUCCESS: "ADD_PRODUCTS_SUCCESS",
  ADD_PRODUCTS_FAILURE: "ADD_PRODUCTS_FAILURE",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};

export const getProductsAction = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
};
